# Generated by Django 5.2 on 2025-04-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('des', models.TextField(null=True)),
                ('image', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserComic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_like', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('background_image', models.CharField(blank=True, null=True)),
                ('image', models.CharField(blank=True, null=True)),
                ('preview_image', models.CharField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('total_chapter', models.IntegerField(blank=True, default=0, null=True)),
                ('reviews', models.JSONField(default={'likes': 0, 'number_of_user_rating': 0, 'rating': 0})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comic.author')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('views', models.IntegerField(default=0)),
                ('src_image', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.comic')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.chapter')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.comic')),
            ],
        ),
    ]
