# Generated by Django 5.1.6 on 2025-03-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='background_image',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
