# Generated by Django 5.1.6 on 2025-03-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_alter_author_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='preview_image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
