# Generated by Django 5.1.6 on 2025-03-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0006_comic_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
