# Generated by Django 5.1.6 on 2025-03-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0007_alter_comic_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='rating',
        ),
        migrations.AddField(
            model_name='comic',
            name='reviews',
            field=models.JSONField(default={'likes': 0, 'number_of_user_rating': 0, 'rating': 0}),
        ),
    ]
